### ISSUE TITLE
TLS configuration

### ISSUE THREAD

**Issue by onitake** [bragfoo/TiPrometheus#1]
From what I can see in conf.go, there is no way to configure TLS certificates, neither for the Prometheus listener, nor for the TiKV client.

If I want to use both client and server authentication, how can I configure the certificates for that? Is TLS support even implemented?

**Comment by 70data** [comment]
This logic has not yet been implemented.
We'll refactor it a little bit later and implement this logic.

**Comment by onitake** [comment]
I went ahead and implemented TLS support: #2 .
If you think there are too many changes, I can also split the PR.

**Comment by 70data** [comment]
It‘s awesome.
If you have any plans I can develop with you.
