### ISSUE TITLE
该项目是否解决了promql存在四种运算符的问题

### ISSUE THREAD

**Issue by sunism** [bragfoo/TiPrometheus#10]
prometheus有以下4中运算符
=: Select labels that are exactly equal to the provided string.
!=: Select labels that are not equal to the provided string.
=~: Select labels that regex-match the provided string.
!~: Select labels that do not regex-match the provided string.
我看代码中在查询时，直接多lable进行拼接，并没有判断运算符的不同。
例如：
up{host="localhost",instance=~"localhost:8080",job!="cadvisor", sunzheng!~"nihao"}
这种请求发送到后台后，会有type字段。目前该项目只有=，这种情况，其他三种条件并没有解决
请求后续有解决码？

**Comment by machinly** [comment]
see #11
