### ISSUE TITLE
project scope

### ISSUE THREAD

**Issue by yeya24** [bragfoo/TiPrometheus#6]
Hi!
This is an interesting project. But I am curious about its scope. Seems it is only an adpter for tikv. Is there any other plans for this project?

**Comment by 70data** [comment]
Now, it`s only an adpter for tikv.
A plan is make a new timeseries database based on tikv, and support custom coprocessor and custom lua script. Adpter will be a plugin.

**Comment by yeya24** [comment]
Thanks. Close this one.
